### ISSUE TITLE
The partially gray map in mapview

### ISSUE THREAD

**Issue by liute62** [mapbox/mapbox-android-demo#811] opened 2018-08-03 23:44 UTC
Hi guys,

  I just find an issue when I load a mapview and GLSurfaceView in the same activity, the mapview just shows gray without tiles if I did zoom in, zoom out or moving the map. Any ideas about what could be a potential issue?

[
![screenshot_20180803-193541](https://user-images.githubusercontent.com/4735285/43670005-68f3976c-973c-11e8-81f3-82edb9ad1227.png)
](url)

The left side is mapview and the right side is a GLSurfaceView.

**Comment by langsmith** [comment] 2018-08-09 22:44
Hey @liute62 , thanks for using Mapbox. Possible to post a video/gif (https://ezgif.com/) so that we can see how the map (doesn't) respond to zooming/movement?   Internet connection can always affect tile loading too.  

@LukasPaczos  any experience with two GLSurfaceViews on the same screen?

**Comment by LukasPaczos** [comment] 2018-08-10 08:15
Hi @liute62! As long as two `GLSurfaceView`s are not overlapping there should be no issues and seeing that the rendering cuts of on a probable tile boundary, I'm guessing it's a different issue. Could you filter your logs by `mbgl` and check if you are not experiencing any timeouts or connection issues?

**Comment by liute62** [comment] 2018-08-10 23:08
Thanks for the reply, here is the gif. It shouldn't be an internet connection issue because it is reproducible every time. Moreover, after I press phone's back button at the map activity and re-enter the activity, the map doesn't work. ( It totally shows a black screen without showing the any map related view). Only when I manually closed the app and re-enter the activity, it works as the gif shows.

![ezgif com-video-to-gif 1](https://user-images.githubusercontent.com/4735285/43984674-d97e4c64-9cb6-11e8-8377-ca146d111943.gif)

The two GLSurfaceView are not overlapping. I check thes mbgl in log and it only shows one line message:

I/mbgl: {GLThread 1912}[General]: GPU Identifier: Adreno (TM) 540

**Comment by liute62** [comment] 2018-09-12 22:10
I may update the question again that the issue shouldn't be caused by GLSurfaceView cause after removing it, it still has.

Here is the new screenshots:

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/4735285/45455542-5448a300-b69c-11e8-9584-cd8dd31c470d.gif)

1.The first is an activity A that holds a mapview, that works fine.
2.After launch another activity B, it shows grey map. When zoom in or zoom out, it makes the whole map gray.
3.After existing from activity B by pressing the back button, the mapview of A becomes a whole grey map.

More details:
1) using com.mapbox.mapboxsdk:mapbox-android-sdk:5.5.2
2) testing phone : google pixel 2
3) A warning appears during operations above: 

 W/.mapbox.com/...: type=1400 audit(0.0:1245): avc: denied { write } for name="perfd" dev="sda45" ino=6782983 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:shell_data_file:s0 tclass=dir permissive=0

4) All two activity handle mapview lifecycle carefully by calling onStart, onPause, onStop, onResume, onDestroy, onLowMemory, onSaveInstanceState

5) The Activity B's mapview is used inside a Framelayout in the xml file while A is not.

6) The initilization is inside Application onCreate by calling and the access token should work.  
     Mapbox.getInstance(this, getString(R.string.access_token));


Thanks for your help.

**Comment by LukasPaczos** [comment] 2018-09-17 12:11
Thanks for additional info @liute62.
I'm unable to reproduce the issue:
![ezgif com-video-to-gif 9](https://user-images.githubusercontent.com/16925074/45622179-6737ea80-ba83-11e8-83fd-58c3b5fee2e2.gif)

Would you be able to retest your setup using `6.5.0` which is the most recent version of the SDK?

**Comment by liute62** [comment] 2018-09-27 00:17
I try the 6.50 version and the problem still exists and here is my dependency list.

    compile ('com.mapbox.mapboxsdk:mapbox-android-sdk:6.5.0')
    compile ('com.mapbox.mapboxsdk:mapbox-android-services:2.2.10')
    compile ('com.mapbox.mapboxsdk:mapbox-java-services:2.2.10')
    compile 'com.mapbox.mapboxsdk:mapbox-android-navigation:0.19.0'
    compile 'com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.19.0'

After another 1 hour debugging, the problem looks to be solved. And I find I was unable to reproduce the bug. I will try to see if this appears again during the further development.

**Comment by langsmith** [comment] 2019-05-14 17:44
Any updates/progress on this, @liute62 ?

**Comment by langsmith** [comment] 2019-06-18 19:48
Closing for now. Happy to re-open and keep the conversation going if we hear back 👍

**Closed by langsmith** 2019-06-18 19:48 UTC
Labels: question :question:
