### ISSUE TITLE
Animated Location Icon example bug

### ISSUE THREAD

**Issue by maximemhd** [mapbox/mapbox-android-demo#377] opened 2017-06-23 13:34 UTC
Hi,
I noticed that if you put a custom style in the XML file, your example doesn't work (the marker appears at coordinates 0,0 but after that nothing appends).
But if you let the default light style in the XML, and then you change the style in the Activity, it works...

**Comment by cammace** [comment] 2017-07-21 00:39
Could you help us reproduce this issue by providing some xml code? 

cc: @langsmith

**Comment by maximemhd** [comment] 2017-07-21 07:59
With this XML it works (the same as in the example):

	<android.support.design.widget.CoordinatorLayout
	xmlns:android="http://schemas.android.com/apk/res/android"
	xmlns:app="http://schemas.android.com/apk/res-auto"
	xmlns:mapbox="http://schemas.android.com/apk/res-auto"
	xmlns:tools="http://schemas.android.com/tools"
	android:layout_width="match_parent"
	android:layout_height="match_parent"
	android:orientation="vertical"
	tools:context="io.github.maximemhd.maaxmap.MainActivity">

    <com.mapbox.mapboxsdk.maps.MapView
        android:id="@+id/mapView"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        mapbox:mapbox_styleUrl="@string/mapbox_style_light"
        mapbox:mapbox_uiRotateGestures="false">

    </com.mapbox.mapboxsdk.maps.MapView>

But with a custom style, it doesn't (this xml) :


      <android.support.design.widget.CoordinatorLayout
      xmlns:android="http://schemas.android.com/apk/res/android"
      xmlns:app="http://schemas.android.com/apk/res-auto"
      xmlns:mapbox="http://schemas.android.com/apk/res-auto"
      xmlns:tools="http://schemas.android.com/tools"
      android:layout_width="match_parent"
      android:layout_height="match_parent"
      android:orientation="vertical"
      tools:context="io.github.maximemhd.maaxmap.MainActivity">

    <com.mapbox.mapboxsdk.maps.MapView
        android:id="@+id/mapView"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
         mapbox:mapbox_styleUrl="mapbox://styles/maximemhd/cj487m11i1q392rph27vlbamc"
        mapbox:mapbox_uiRotateGestures="false">
    </com.mapbox.mapboxsdk.maps.MapView>

      </android.support.design.widget.CoordinatorLayout>

Here is the commit in my project that make it work:
[Update to solve bug](https://github.com/maximemhd/MaaxAndroidMap/commit/e345ac5d9e46eb56135efd2642cdb17680461da4)
The previous one didn't:
[Initial commit](https://github.com/maximemhd/MaaxAndroidMap/commit/971c183b9ee0fa38d0aa2dd08b7ee05763538dd1)

I hope it will help.

**Comment by langsmith** [comment] 2017-08-02 22:01
With the introduction of [the Location Layer plugin](https://github.com/mapbox/mapbox-plugins-android/tree/master/plugins/locationlayer/src/main/java/com/mapbox/mapboxsdk/plugins/locationlayer), [we have removed all of the location examples from the demo app](https://github.com/mapbox/mapbox-android-demo/pull/424).

Closing this because it's no longer present in the app. Thank you for reaching out @maximemhd and for your work on hunting down the bug. Although it's no longer applicable to the demo app, I will look into it and see if it's something we need to be aware of moving forward.

**Comment by langsmith** [comment] 2017-08-03 18:52
Thank you for reaching out @maximemhd and for providing lots of information.

I will close this issue because [We have removed all location examples in the demo app](https://github.com/mapbox/mapbox-android-demo/pull/424). We did this because [we now have a location layer plugin](https://github.com/mapbox/mapbox-plugins-android/tree/master/plugins/locationlayer/src/main/java/com/mapbox/mapboxsdk/plugins/locationlayer).

**Closed by langsmith** 2017-08-03 18:52 UTC
Labels: bug
