### ISSUE TITLE
Demo app crashes when opening plugins/PlaceSelectionPluginActivity (Place picker)

### ISSUE THREAD

**Issue by pengdev** [mapbox/mapbox-android-demo#1247] opened 2019-10-11 11:31 UTC
Crash log:
```
2019-10-11 15:44:09.930 12899-12899/com.mapbox.mapboxandroiddemo.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.mapbox.mapboxandroiddemo.debug, PID: 12899
    java.lang.IllegalArgumentException: Illegal state argument: 5
        at com.google.android.material.bottomsheet.BottomSheetBehavior.startSettlingAnimation(BottomSheetBehavior.java:1099)
        at com.google.android.material.bottomsheet.BottomSheetBehavior.startSettlingAnimationPendingLayout(BottomSheetBehavior.java:886)
        at com.google.android.material.bottomsheet.BottomSheetBehavior.setState(BottomSheetBehavior.java:865)
        at com.mapbox.mapboxsdk.plugins.places.picker.ui.CurrentPlaceSelectionBottomSheet.toggleBottomSheet(CurrentPlaceSelectionBottomSheet.java:80)
        at com.mapbox.mapboxsdk.plugins.places.picker.ui.CurrentPlaceSelectionBottomSheet.setPlaceDetails(CurrentPlaceSelectionBottomSheet.java:55)
        at com.mapbox.mapboxsdk.plugins.places.picker.ui.PlacePickerActivity.onCameraIdle(PlacePickerActivity.java:165)
        at com.mapbox.mapboxsdk.maps.CameraChangeDispatcher.executeOnCameraIdle(CameraChangeDispatcher.java:140)
        at com.mapbox.mapboxsdk.maps.CameraChangeDispatcher.access$300(CameraChangeDispatcher.java:21)
        at com.mapbox.mapboxsdk.maps.CameraChangeDispatcher$CameraChangeHandler.handleMessage(CameraChangeDispatcher.java:177)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:7029)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by langsmith** [comment] 2019-10-11 13:22
Duplicate of https://github.com/mapbox/mapbox-android-demo/issues/1164

**Closed by langsmith** 2019-10-11 13:22 UTC
Labels: crash :boom:
