### ISSUE TITLE
MapSnapshotter with addMarker addPolyline

### ISSUE THREAD

**Issue by xhAndroid** [mapbox/mapbox-android-demo#1249] opened 2019-10-18 08:45 UTC
v6.8.1
How to The screenshot contains markers and lines ？

**Comment by langsmith** [comment] 2019-10-22 00:28
Closing because this is a duplicate of the now-resolved and now-closed https://github.com/mapbox/mapbox-android-demo/issues/1250

**Closed by langsmith** 2019-10-22 00:28 UTC
