### ISSUE TITLE
when cluster marker clicked zoom somewhere else

### ISSUE THREAD

**Issue by PhloxDev** [mapbox/mapbox-android-demo#1165] opened 2019-08-08 12:11 UTC
when two markers be near together and click on cluster marker zoom somewhere else and not show markers.

![ezgif com-optimize](https://user-images.githubusercontent.com/23661966/62701096-af902c00-b9f8-11e9-8ad6-3c6043164628.gif)

It's my cluster click code

```
private void onClusterClick(Feature cluster, Point clickPoint, GeoJsonSource source) {

        double nextZoomLevel = source.getClusterExpansionZoom(cluster);
        double zoomDelta = nextZoomLevel - mapboxMap.getCameraPosition().zoom;

        mapboxMap.animateCamera(CameraUpdateFactory.zoomBy(zoomDelta + 0.01, clickPoint));
    }
```

if clusterMaxZoom=8 or less zoom properly but markers overlap and not show both

**Comment by LukasPaczos** [comment] 2019-08-12 09:24
Closing as a duplicate of https://github.com/mapbox/mapbox-gl-native/issues/15348.

**Closed by LukasPaczos** 2019-08-12 09:24 UTC
Labels: question :question:
