### ISSUE TITLE
Simple Offline map crashes in Google Play version

### ISSUE THREAD

**Issue by roblabs** [mapbox/mapbox-android-demo#144] opened 2016-09-13 00:00 UTC
Both the Google Play version and my local copy of `map box-android-demo` crash when testing the activity `SimpleOfflineMapActivity`.

* Related to https://github.com/mapbox/mapbox-gl-native/issues/6193
* compiled with `compile('com.mapbox.mapboxsdk:mapbox-android-sdk:4.2.0-beta.2@aar')`
* local testing with [commits pulled in locally](https://github.com/roblabs/mapbox-gl-native/pull/1) are promising, but be sure to follow [#6193](https://github.com/mapbox/mapbox-gl-native/issues/6193) for latest

Offending line from Native Library — 
` "terminating with uncaught exception of type mapbox::sqlite::Exception: unable to open database file" failed`

```
09-12 16:53:04.851 10788-10950/? A/libc: /Volumes/Android/buildbot/src/android/ndk-r12-release/ndk/sources/cxx-stl/llvm-libc++abi/libcxxabi/src/abort_message.cpp:74: void abort_message(const char *, ...): assertion "terminating with uncaught exception of type mapbox::sqlite::Exception: unable to open database file" failed
09-12 16:53:04.851 10788-10950/? A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 10950 (DefaultFileSour)
09-12 16:53:04.952 9000-9000/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
09-12 16:53:04.953 9000-9000/? A/DEBUG: Build fingerprint: 'google/hammerhead/hammerhead:6.0.1/MOB31E/3142026:user/release-keys'
09-12 16:53:04.953 9000-9000/? A/DEBUG: Revision: '11'
09-12 16:53:04.953 9000-9000/? A/DEBUG: ABI: 'arm'
09-12 16:53:04.953 9000-9000/? A/DEBUG: pid: 10788, tid: 10950, name: DefaultFileSour  >>> com.mapbox.mapboxandroiddemo <<<
09-12 16:53:04.953 9000-9000/? A/DEBUG: signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
09-12 16:53:04.979 9000-9000/? A/DEBUG: Abort message: '/Volumes/Android/buildbot/src/android/ndk-r12-release/ndk/sources/cxx-stl/llvm-libc++abi/libcxxabi/src/abort_message.cpp:74: void abort_message(const char *, ...): assertion "terminating with uncaught exception of type mapbox::sqlite::Exception: unable to open database file" failed'

```

**Comment by cammace** [comment] 2016-09-21 20:03
Sounds like you were running into issue https://github.com/mapbox/mapbox-gl-native/issues/6193 which has been resolved in the SNAPSHOT and beta 3. Unable to reproduce on my end now, thanks for reporting!

**Closed by cammace** 2016-09-21 20:03 UTC
