### ISSUE TITLE
OutOfMemory  BitmapFactory

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-android-demo#245] opened 2017-03-20 13:35 UTC
```java
arrow_drop_down
Exception java.lang.OutOfMemoryError:
android.graphics.BitmapFactory.nativeDecodeAsset (BitmapFactory.java)
android.graphics.BitmapFactory.decodeStream (BitmapFactory.java:595)
android.graphics.BitmapFactory.decodeResourceStream (BitmapFactory.java:430)
android.graphics.drawable.Drawable.createFromResourceStream (Drawable.java:856)
android.content.res.Resources.loadDrawable (Resources.java:2124)
android.content.res.TypedArray.getDrawable (TypedArray.java:602)
android.widget.ImageView.<init> (ImageView.java:129)
android.support.v7.widget.p.<init> ()
android.support.v7.widget.p.<init> ()
android.support.v7.app.o.a ()
android.support.v7.app.m.c ()
android.support.v7.app.m.a ()
android.support.v4.h.m$a.onCreateView ()
android.view.LayoutInflater.createViewFromTag (LayoutInflater.java:684)
android.view.LayoutInflater.rInflate (LayoutInflater.java:755)
android.view.LayoutInflater.rInflate (LayoutInflater.java:758)
android.view.LayoutInflater.inflate (LayoutInflater.java:492)
android.view.LayoutInflater.inflate (LayoutInflater.java:397)
com.mapbox.mapboxandroiddemo.a.a.b ()
android.support.v7.widget.RecyclerView$a.c ()
android.support.v7.widget.RecyclerView$o.a ()
android.support.v7.widget.RecyclerView$o.a ()
android.support.v7.widget.RecyclerView$o.c ()
android.support.v7.widget.LinearLayoutManager$c.a ()
android.support.v7.widget.LinearLayoutManager.a ()
android.support.v7.widget.LinearLayoutManager.a ()
android.support.v7.widget.LinearLayoutManager.c ()
android.support.v7.widget.RecyclerView.N ()
android.support.v7.widget.RecyclerView.onMeasure ()
android.view.View.measure (View.java:16650)
android.widget.LinearLayout.measureHorizontal (LinearLayout.java:1034)
android.widget.LinearLayout.onMeasure (LinearLayout.java:590)
android.view.View.measure (View.java:16650)
android.view.ViewGroup.measureChildWithMargins (ViewGroup.java:5129)
android.support.design.widget.CoordinatorLayout.a ()
android.support.design.widget.k.a ()
android.support.design.widget.AppBarLayout$ScrollingViewBehavior.a ()
android.support.design.widget.CoordinatorLayout.onMeasure ()
android.view.View.measure (View.java:16650)
android.support.v4.widget.DrawerLayout.onMeasure ()
android.view.View.measure (View.java:16650)
android.view.ViewGroup.measureChildWithMargins (ViewGroup.java:5129)
android.widget.FrameLayout.onMeasure (FrameLayout.java:310)
android.support.v7.widget.ContentFrameLayout.onMeasure ()
android.view.View.measure (View.java:16650)
android.view.ViewGroup.measureChildWithMargins (ViewGroup.java:5129)
android.widget.LinearLayout.measureChildBeforeLayout (LinearLayout.java:1404)
android.widget.LinearLayout.measureVertical (LinearLayout.java:695)
android.widget.LinearLayout.onMeasure (LinearLayout.java:588)
android.view.View.measure (View.java:16650)
android.view.ViewGroup.measureChildWithMargins (ViewGroup.java:5129)
android.widget.FrameLayout.onMeasure (FrameLayout.java:310)
android.view.View.measure (View.java:16650)
android.view.ViewGroup.measureChildWithMargins (ViewGroup.java:5129)
android.widget.LinearLayout.measureChildBeforeLayout (LinearLayout.java:1404)
android.widget.LinearLayout.measureVertical (LinearLayout.java:695)
android.widget.LinearLayout.onMeasure (LinearLayout.java:588)
android.view.View.measure (View.java:16650)
android.view.ViewGroup.measureChildWithMargins (ViewGroup.java:5129)
android.widget.FrameLayout.onMeasure (FrameLayout.java:310)
```

[Mapping file](https://gist.github.com/tobrun/39e0582ad329f57e8cdbc61dbdf0f5c9)

**Comment by langsmith** [comment] 2017-05-25 17:31
Do we know if this was a one-time error or something that's reproducible?

**Comment by langsmith** [comment] 2017-05-30 16:57
@zugaldia , I think I'll need some help with figuring out this ticket if it's a recurring problem that needs addressing in this milestone...

**Comment by tobrun** [comment] 2017-05-30 18:24
Are you still seeing this exception in the developer console with newer versions? 
if yes, is that stacktrace obfuscated? (you can upload the mapping file to deobfuscate them). 
LMK if you need more information on that process.

**Comment by langsmith** [comment] 2017-06-19 20:24
@tobrun , you're talking about the Firebase console?

**Comment by tobrun** [comment] 2017-06-20 08:29
Yes ;)

**Comment by langsmith** [comment] 2017-06-21 16:53
Closing this because @tobrun has stated that he "took quick look but there isn’t anything there with the new console"

**Closed by langsmith** 2017-06-21 16:53 UTC
